# Generated by Django 3.0.3 on 2020-04-28 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('start_point', models.CharField(max_length=50)),
                ('destination', models.CharField(max_length=50)),
                ('time', models.CharField(max_length=50)),
                ('class_type', models.CharField(max_length=20)),
                ('tickets', models.IntegerField()),
                ('cost', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lattitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='main',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='seat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.CharField(max_length=50)),
                ('occupied', models.IntegerField()),
                ('date', models.DateField()),
                ('start_point', models.CharField(max_length=50)),
                ('destination', models.CharField(max_length=50)),
                ('time', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('slots', models.IntegerField()),
                ('class_type', models.TextField()),
                ('base_fare', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=20)),
                ('email', models.TextField(max_length=50)),
                ('gender', models.TextField(max_length=20)),
                ('age', models.IntegerField()),
                ('number', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
