# Generated by Django 3.0.3 on 2020-02-27 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=20)),
                ('date', models.DateTimeField()),
                ('start_point', models.CharField(max_length=50)),
                ('destination', models.CharField(max_length=50)),
                ('time', models.TimeField()),
                ('class_type', models.CharField(max_length=20)),
                ('tickets', models.IntegerField()),
                ('cost', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='ticket',
            name='slots',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=20),
        ),
    ]
