# Generated by Django 3.0.3 on 2020-03-04 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200229_2024'),
    ]

    operations = [
        migrations.CreateModel(
            name='seat_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occupied', models.IntegerField()),
                ('date', models.DateField()),
                ('start_point', models.CharField(max_length=50)),
                ('destination', models.CharField(max_length=50)),
                ('time', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.TextField(max_length=50),
        ),
    ]
