# Generated by Django 3.0.3 on 2020-02-28 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200227_2314'),
    ]

    operations = [
        migrations.CreateModel(
            name='routes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_point', models.CharField(max_length=50)),
                ('destination', models.CharField(max_length=50)),
                ('distance', models.FloatField()),
                ('price', models.FloatField()),
            ],
        ),
    ]
